# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm-setup-node

      - name: Cache pnpm store
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm lint
      - run: pnpm sdk build
      - run: pnpm build:examples
      - run: docker compose -f docker/docker-compose-ci.yml up --build -d
      - run: pnpm sdk test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run benchmark
        run: pnpm sdk test:bench

      - name: compress size check
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'sdk build'
          exclude: '{**/*.map,**/node_modules/**,**/dist/chunk-*.{js,cjs,mjs}}'
          pattern: './packages/sdk/dist/**/*.{js,mjs}'
