name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: './packages/sdk/pnpm-lock.yaml'
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'pnpm sdk build'
          exclude: '{**/*.map,**/node_modules/**,**/dist/chunk-*.{js,cjs,mjs}}'
          pattern: './packages/sdk/dist/**/*.{js,mjs}'
